test_task:
  auto_cancellation: true
  container:
    image: gradle:jdk8
    cpu: 8
    memory: 24G
  setup_workspace_script: |
    chmod +x ./gradlew
    rm -rf $CIRRUS_WORKING_DIR/src/main/resources/build.txt
    echo $CIRRUS_BUILD_ID > $CIRRUS_WORKING_DIR/src/main/resources/build.txt
  gradle_cache:
    folder: ~/.gradle/caches
    fingerprint_script: |
      cat build.gradle
      cat gradle/wrapper/gradle-wrapper.properties
    populate_script: ./gradlew setupDevWorkspace
  build_script: |
    ./gradlew test
    ./gradlew build
  jar_artifacts:
    path: ./build/libs/**
  always:
    cleanup_before_cache_script: |
      rm -rf ~/.gradle/caches/$GRADLE_VERSION/
      find ~/.gradle/caches/ -name "*.lock" -type f -delete
