task:
  auto_cancellation: $CIRRUS_PR != ''
  container:
    image: gradle:jdk8
    cpu: 4
    memory: 12G
  setup_workspace_script: chmod +x ./gradlew
  gradle_cache:
    folder: ~/.gradle/caches
    fingerprint_script: |
      cat build.gradle
      cat gradle/wrapper/gradle-wrapper.properties
    populate_script: ./gradlew setupDevWorkspace
  matrix:
  - name: Build Job
    script: |
      rm -rf $CIRRUS_WORKING_DIR/src/main/resources/build.txt
      echo $CIRRUS_BUILD_ID > $CIRRUS_WORKING_DIR/src/main/resources/build.txt
      ./gradlew build
    jar_artifacts:
      path: ./build/libs/**
  - name: Test Job
    script: |
      ./gradlew test
  always:
    cleanup_before_cache_script: |
      # Docker image version:
      rm -rf ~/.gradle/caches/$GRADLE_VERSION/
      # Wrapper version:
      rm -rf ~/.gradle/caches/4.0.2/
      # Lockfiles:
      find ~/.gradle/caches/ -name "*.lock" -type f -delete
